// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANd0-XpsgnWh6Gcg7XYbPJwOWH6i-RDHY',
    appId: '1:294372940295:web:8d321a9ddb40472afc28a2',
    messagingSenderId: '294372940295',
    projectId: 'busguideapp22',
    authDomain: 'busguideapp22.firebaseapp.com',
    storageBucket: 'busguideapp22.firebasestorage.app',
    measurementId: 'G-74WDE1L70T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd49WpvU0CDLd8qdknaC7Evq38cXPseaM',
    appId: '1:294372940295:android:1c9d74117d9c82f5fc28a2',
    messagingSenderId: '294372940295',
    projectId: 'busguideapp22',
    storageBucket: 'busguideapp22.firebasestorage.app',
  );

}